version: "3.9"
services:
    db:
        image: postgres:12
        env_file: ./backend/.env
        volumes:
            - ~/pgsql/db:/var/lib/postgresql/data/
        networks:
            - default
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    backend:
        container_name: essenvia_backend
        build:
            dockerfile: backend/Dockerfile
            context: .
        env_file: ./backend/.env
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app/backend
        stdin_open: true  # for testing
        tty: true  # for testing
        command: "sh entrypoint.sh"
        depends_on:
            - db
